base-100: "#10101C"
base-200: "#17172A"
base-300: "#292744"
primary: "#3A86FF"
secondary: "#FF006E"
accent: "#8338EC"
neutral: "#F4F1DE"
info: "#3A86FF"
success: "#3A86FF"
warning: "#FFBE0B"
error: "#FB5607"