base-100: "#FFFFFF"
base-200: "#CBF3F0"
base-300: "#FFBF69"
primary: "#2EC4B6"
secondary: "#FF9F1C"
accent: "#3A86FF"
neutral: "#24323A"
info: "#3A86FF"
success: "#2EC4B6"
warning: "#FF9F1C"
error: "#FB5607"